Added League of Legends (Riot Games) API support
abaddonpuff/commandCenter pull request #17
Opened 2024-05-24 03:52 UTC by abaddonpuff

Added support for the League of Legends API, It now obtains all games for a particular player.

2024-05-24 09:02 UTC, bbelderbos requested changes
Looks good, a few suggestions to make it better. What's next?

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +LEAGUE_API_KEY = os.getenv('LEAGUE_API_KEY')
Fine for now, later we have the user store these encrypted in the db

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +    headers={
this can be de-duplicated, you can turn it into a constant at the top of the module

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +def get_league_summoner(summoner=None, tag_id=None):
I would make these required args

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +def get_league_games_by_summoner_name(summoner=None, tag_id=None, start_time=0, endtime=0, count=20):
same here, I think the first two args are required ...

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +    puuid = get_league_summoner(summoner, tag_id)
this could also be an argument to the function, then there is less of a dependency of one function on another one

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +from requests_oauthlib import OAuth1Session
not too urgent, but check PEP8 import order for styling (you can use isort + pre-commit to automate this)

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +from dotenv import load_dotenv, find_dotenv
seems  `find_dotenv` is not used

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +#DEFINE AUTHENTICATION TOKENS
seems redundant comment

2024-05-24 09:02 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +#DEFINE URLS
comment can be removed

2024-05-24 18:42 UTC, bbelderbos commented
Only saw this today, any more progress?

2024-05-25 21:22 UTC, abaddonpuff commented on commandCenter/centralHub/league/leagueAPI.py
> +    headers={
Question on this, the games would be different depending on the summoner. Summoner = player, the puuid is the game identifier for a player. Would this still need to be a constant?

2024-05-25 21:23 UTC, abaddonpuff commented on commandCenter/centralHub/league/leagueAPI.py
> +def get_league_summoner(summoner=None, tag_id=None):
Will commit to the next PR

2024-05-25 21:24 UTC, merged

2024-05-27 09:57 UTC, bbelderbos commented on commandCenter/centralHub/league/leagueAPI.py
> +    headers={
but that's the url right? comparing the header dicts, they seemed static = having the same content?